// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrCm8lc5QKvfjmdUOurouVt7JO7TYJjc',
    appId: '1:513397517704:web:334b65d2518c08d4229e3d',
    messagingSenderId: '513397517704',
    projectId: 'futuristauthproj',
    authDomain: 'futuristauthproj.firebaseapp.com',
    storageBucket: 'futuristauthproj.firebasestorage.app',
    measurementId: 'G-JSJ07TXJXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzX3fq7dIBVxPBCzFDRDBd8cg5LCUlor0',
    appId: '1:513397517704:android:4f96e4ed8705b62d229e3d',
    messagingSenderId: '513397517704',
    projectId: 'futuristauthproj',
    storageBucket: 'futuristauthproj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsibWHfHXcLHrrlFIa24zwFnxWpVxNtBI',
    appId: '1:513397517704:ios:e10d4e7053cab18e229e3d',
    messagingSenderId: '513397517704',
    projectId: 'futuristauthproj',
    storageBucket: 'futuristauthproj.firebasestorage.app',
    iosBundleId: 'com.example.futuristProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsibWHfHXcLHrrlFIa24zwFnxWpVxNtBI',
    appId: '1:513397517704:ios:e10d4e7053cab18e229e3d',
    messagingSenderId: '513397517704',
    projectId: 'futuristauthproj',
    storageBucket: 'futuristauthproj.firebasestorage.app',
    iosBundleId: 'com.example.futuristProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJrCm8lc5QKvfjmdUOurouVt7JO7TYJjc',
    appId: '1:513397517704:web:c27e3814706ad1d4229e3d',
    messagingSenderId: '513397517704',
    projectId: 'futuristauthproj',
    authDomain: 'futuristauthproj.firebaseapp.com',
    storageBucket: 'futuristauthproj.firebasestorage.app',
    measurementId: 'G-RXG12XF2Y9',
  );

}